# Generated by Django 5.0.6 on 2024-07-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_created']},
        ),
    ]
